print('''
lista = [0, 1, 2, 3, 4, 5, 6]
-----''')
print('''slice -> sector(fracción)
guardar sectores para usarlas mas tarde,
si hubiera que cambiar solo habria cambiamos la variable''')
print('''-----''')
lista = [0, 1, 2, 3, 4, 5, 6]
print('''
lista_corte = slice(2) -> slice(empieza, acaba, intervalo)
print(lista_corte)
print(lista[lista_corte])''')
lista_corte = slice(2)
print(lista_corte)
print(lista[lista_corte])
print('''-----''')
print('corte_variado = slice(1, 4, 2)')
corte_variado = slice(1, 4, 2)
print('''-----''')
print('print(lista[1:4:2])')
print(lista[1:4:2])
print('print(lista[corte_variado])')
print(lista[corte_variado])
print('''-----''')
print('Saber donde esta el rango de una variable')
print('print(corte_variado.start) empieza')
print(corte_variado.start)
print('print(corte_variado.stop) acaba')
print(corte_variado.stop)
print('print(corte_variado.step) intervalo')
print(corte_variado.step)